version: '3'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
  back:
    build:
      dockerfile: Dockerfile
      context: ./back
    ports:
      - '8066:8066'
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/postgres

volumes:
  postgres_data: